name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          make
      - name: Upload Artifacts
        uses: actions/upload-artifact@v3  # Updated to v3
        with:
          name: built-artifact
          path: main

